modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
#issueTrackerURL=""
[[mods]]
modId="domesticdecor"
version="${file.jarVersion}"
displayName="Domestic Decor"
#updateJSONURL=""
#displayURL=""
logoFile="logo.png"
credits=""
authors=""
description='''
'''
[[dependencies.domesticdecor]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.domesticdecor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
